project_id = "kwsbzfvvmazyhmjgxryo"

[functions.chat-gemini]
verify_jwt = true

[functions.process-file]
verify_jwt = true

[functions.assistant-chat]
verify_jwt = true

[functions.ai-health]
verify_jwt = false

[functions.legal-search]
verify_jwt = false

[functions.legal-document-processor]
verify_jwt = false

[functions.email-corpus-processor]
verify_jwt = true

[functions.enterprise-evidence-search]
verify_jwt = true

[functions.nsw-legal-ingestor]
verify_jwt = true

[functions.enhanced-evidence-processor]
verify_jwt = true

[functions.enhanced-memory-processor]
verify_jwt = true

[functions.continuous-case-analysis]
verify_jwt = true

[functions.categorize-file]
verify_jwt = true

[functions.evidence-intelligence-orchestrator]
verify_jwt = true

[functions.evidence-legal-analyzer]
verify_jwt = true

[functions.extract-timeline]
verify_jwt = true


[functions.ingest-text]
verify_jwt = true

[functions.memory-manager]
verify_jwt = true

[functions.nsw-rag-assistant]
verify_jwt = true

[functions.test-assistant-chat]
verify_jwt = true

[functions.find-nsw-resources]
verify_jwt = false
