project_id = "kwsbzfvvmazyhmjgxryo"

[functions.assistant-chat]
verify_jwt = true

[functions.ai-health]
verify_jwt = false

[functions.legal-search]
verify_jwt = false

[functions.legal-document-processor]
verify_jwt = true

[functions.email-corpus-processor]
verify_jwt = true

[functions.enterprise-evidence-search]
verify_jwt = true
