// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwsbzfvvmazyhmjgxryo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3c2J6ZnZ2bWF6eWhtamd4cnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDc0NzYsImV4cCI6MjA3MDQ4MzQ3Nn0.cJ0_VypyZB3kor1GVIIvM5byOZBTmwf8Sc9CO7qTEuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});